### ISSUE TITLE
Answer options not recognized

### ISSUE THREAD

**Issue by Yeethaven** [coalbl4ck/StudExam-ChatGPT#1]
First of all, I love the creativity and the idea!

Sadly, the script only recognizes the question and not the provided possible answers, so it won't be much use for most questions...
(Example: "Which of these functions is differentiable?" - ChatGPT will just make up some functions and then tell you which of them are differentiable)

Also, you might really want to delete the version before the "removed private key" commit and delete/change your OpenAI API key, it is still visible in the GitHub changelog :)

**Comment by BillGatesPriv** [comment]
Thanks man!

I know. I didn't have enough time at hand yesterday to also make it work with different questions. 
Also I have to check if ChatGPT can answer MC-Questions. 

Thanks for the heads up, already changed the key when I realized that i messed up. :+1:
